Repository WaldiNet/Towers_Of_The_Wild_Reworked, pull requests merged in 2021-12, with the labels that each got.

#3 GH-2 - Add support for fabric waystones
  .gitignore
  README.md
  build.gradle
  gradle.properties
  src/main/java/waldinet/towers_of_the_wild_reworked/TowersOfTheWildReworked.java
  src/main/java/waldinet/towers_of_the_wild_reworked/generator/AbstractTowerGenerator.java
  src/main/java/waldinet/towers_of_the_wild_reworked/generator/DerelictGrassTowerGenerator.java
  src/main/java/waldinet/towers_of_the_wild_reworked/generator/DerelictTowerGenerator.java
  src/main/java/waldinet/towers_of_the_wild_reworked/generator/IceTowerGenerator.java
  src/main/java/waldinet/towers_of_the_wild_reworked/generator/JungleTowerGenerator.java
  src/main/java/waldinet/towers_of_the_wild_reworked/generator/OceanTowerGenerator.java
  src/main/java/waldinet/towers_of_the_wild_reworked/generator/OceanWarmTowerGenerator.java
  src/main/java/waldinet/towers_of_the_wild_reworked/generator/RegularTowerGenerator.java
  src/main/java/waldinet/towers_of_the_wild_reworked/structure/DerelictTowerStructure.java
  src/main/java/waldinet/towers_of_the_wild_reworked/structure/OceanTowerStructure.java
  src/main/java/waldinet/towers_of_the_wild_reworked/structure/TowerStructure.java
  src/main/java/waldinet/towers_of_the_wild_reworked/utils/ModUtils.java
  src/main/resources/data/towers_of_the_wild_reworked/structures/derelict/fabric_waystone_derelict_tower_top.nbt
  src/main/resources/data/towers_of_the_wild_reworked/structures/derelict_grass/fabric_waystone_derelict_grass_tower_top.nbt
  src/main/resources/data/towers_of_the_wild_reworked/structures/ice/fabric_waystone_ice_tower_top.nbt
  src/main/resources/data/towers_of_the_wild_reworked/structures/jungle/fabric_waystone_jungle_tower_top.nbt
  src/main/resources/data/towers_of_the_wild_reworked/structures/ocean/fabric_waystone_ocean_tower_top.nbt
  src/main/resources/data/towers_of_the_wild_reworked/structures/ocean_warm/fabric_waystone_ocean_warm_tower_top.nbt
  src/main/resources/data/towers_of_the_wild_reworked/structures/regular/fabric_waystone_tower_top.nbt
  src/main/resources/fabric.mod.json
  src/main/resources/towers_of_the_wild_reworked.mixins.json
Labels: enhancement

#5 GH-4 - Add support for 1.18.1
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/build.yml
  CHANGELOG.md
  README.md
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/waldinet/towers_of_the_wild_reworked/TowersOfTheWildReworked.java
  src/main/java/waldinet/towers_of_the_wild_reworked/generator/DerelictGrassTowerGenerator.java
  src/main/java/waldinet/towers_of_the_wild_reworked/generator/DerelictTowerGenerator.java
  src/main/java/waldinet/towers_of_the_wild_reworked/generator/RegularTowerGenerator.java
  src/main/java/waldinet/towers_of_the_wild_reworked/structure/DerelictTowerStructure.java
  src/main/java/waldinet/towers_of_the_wild_reworked/structure/OceanTowerStructure.java
  src/main/java/waldinet/towers_of_the_wild_reworked/structure/TowerStructure.java
  src/main/java/waldinet/towers_of_the_wild_reworked/utils/RegUtils.java
  src/main/resources/data/towers_of_the_wild_reworked/structures/derelict_grass/fabric_waystone_derelict_grass_tower_top.nbt
  src/main/resources/data/towers_of_the_wild_reworked/structures/derelict_grass/waystone_derelict_grass_tower_top.nbt
  src/main/resources/fabric.mod.json
  src/main/resources/towers_of_the_wild_reworked.mixins.json
Labels: enhancement, help wanted

#8 Add zh_cn localization
  src/main/resources/assets/towers_of_the_wild_reworked/lang/zh_cn.json
Labels: enhancement

#10 GH-7 - Added translation fallback
  .gitignore
  CHANGELOG.md
  src/main/resources/assets/towers_of_the_wild_reworked/lang/en_us.json
  src/main/resources/assets/towers_of_the_wild_reworked/lang/zh_cn.json
  src/main/resources/data/towers_of_the_wild_reworked/advancements/derelict_grass_tower.json
  src/main/resources/data/towers_of_the_wild_reworked/advancements/derelict_tower.json
  src/main/resources/data/towers_of_the_wild_reworked/advancements/ice_tower.json
  src/main/resources/data/towers_of_the_wild_reworked/advancements/jungle_tower.json
  src/main/resources/data/towers_of_the_wild_reworked/advancements/ocean_tower.json
  src/main/resources/data/towers_of_the_wild_reworked/advancements/ocean_warm_tower.json
  src/main/resources/data/towers_of_the_wild_reworked/advancements/regular_tower.json
  src/main/resources/data/towers_of_the_wild_reworked/advancements/root.json
Labels: bug, enhancement

#11 Create es_cl.json
  src/main/resources/assets/towers_of_the_wild_reworked/lang/es_cl.json
Labels: enhancement
